Update surgeWarp.yml

diff --git a/.github/workflows/surgeWarp.yml b/.github/workflows/surgeWarp.yml
--- a/.github/workflows/surgeWarp.yml
+++ b/.github/workflows/surgeWarp.yml
@@ -24,16 +24,16 @@ jobs:
         sed -i '/\[Proxy\]/d' extracted_content || echo "Failed to delete [Proxy] lines"
 
         # 在提取的内容后追加一行，写入字符串：[Proxy Group]
-        echo -e "\n[Proxy Group]" >> extracted_content || echo "Failed to append [Proxy Group]"
+        # echo -e "\n[Proxy Group]" >> extracted_content || echo "Failed to append [Proxy Group]"
 
         # 检查 extracted.conf 文件是否存在
         if [ ! -f extracted.conf ]; then
           echo "extracted.conf does not exist"
         fi
 
-        # 读取 extracted.conf 文件的内容，然后将其中的 [Proxy Group] 替换为步骤1修改后的内容
-        sed '/\[Proxy Group\]/r extracted_content' extracted.conf | sed '/\[Proxy Group\]/d' > surgeWarp.conf || echo "Failed to create surgeWarp.conf"
-
+        # 读取 extracted.conf 文件的内容，然后将extracted_content插入到extracted.conf中的[Proxy]后面
+        sed '/\[Proxy\]/r extracted_content' extracted.conf  > surgeWarp.conf || echo "Failed to create surgeWarp.conf"
+        
         # 删除临时文件
         rm downloaded_file extracted_content || echo "Failed to delete temporary files"
 
